<a href="https://colab.research.google.com/github/Spandana2704/DL/blob/main/WEEK4_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.random.seed(0)

X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])

def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)

class MLP:
    def __init__(self):
        self.W1 = np.random.randn(2,2)
        self.b1 = np.zeros((1,2))
        self.W2 = np.random.randn(2,1)
        self.b2 = np.zeros((1,1))

    def forward(self,X):
        self.z1 = np.dot(X,self.W1)+self.b1
        self.a1 = sigmoid(self.z1)
        self.z2 = np.dot(self.a1,self.W2)+self.b2
        self.a2 = sigmoid(self.z2)
        return self.a2

    def backward(self,X,Y):
        m = X.shape[0]
        dz2 = self.a2 - Y
        dW2 = np.dot(self.a1.T,dz2)/m
        db2 = np.sum(dz2,axis=0,keepdims=True)/m
        dz1 = np.dot(dz2,self.W2.T)*dsigmoid(self.a1)
        dW1 = np.dot(X.T,dz1)/m
        db1 = np.sum(dz1,axis=0,keepdims=True)/m
        return dW1,db1,dW2,db2

In [ ]:
def train_bgd(model,epochs=10000,lr=0.1):
    for i in range(epochs):
        model.forward(X)
        dW1,db1,dW2,db2 = model.backward(X,Y)
        model.W1 -= lr*dW1
        model.b1 -= lr*db1
        model.W2 -= lr*dW2
        model.b2 -= lr*db2

model = MLP()
train_bgd(model)

print("BGD Output:")
print(np.round(model.forward(X)))

BGD Output:
[[0.]
 [0.]
 [1.]
 [1.]]


In [ ]:
def train_sgd(model,epochs=10000,lr=0.1):
    for i in range(epochs):
        for j in range(len(X)):
            x = X[j:j+1]
            y = Y[j:j+1]
            model.forward(x)
            dW1,db1,dW2,db2 = model.backward(x,y)
            model.W1 -= lr*dW1
            model.b1 -= lr*db1
            model.W2 -= lr*dW2
            model.b2 -= lr*db2

model = MLP()
train_sgd(model)

print("SGD Output:")
print(np.round(model.forward(X)))

SGD Output:
[[0.]
 [1.]
 [1.]
 [0.]]


In [ ]:
def train_minibatch(model,epochs=10000,lr=0.1,batch=2):
    for i in range(epochs):
        for j in range(0,len(X),batch):
            x = X[j:j+batch]
            y = Y[j:j+batch]
            model.forward(x)
            dW1,db1,dW2,db2 = model.backward(x,y)
            model.W1 -= lr*dW1
            model.b1 -= lr*db1
            model.W2 -= lr*dW2
            model.b2 -= lr*db2

model = MLP()
train_minibatch(model)

print("MiniBatch Output:")
print(np.round(model.forward(X)))

MiniBatch Output:
[[0.]
 [1.]
 [1.]
 [0.]]


In [ ]:
def train_momentum(model,epochs=10000,lr=0.1,beta=0.9):
    vW1=np.zeros_like(model.W1)
    vb1=np.zeros_like(model.b1)
    vW2=np.zeros_like(model.W2)
    vb2=np.zeros_like(model.b2)

    for i in range(epochs):
        model.forward(X)
        dW1,db1,dW2,db2 = model.backward(X,Y)

        vW1 = beta*vW1 + (1-beta)*dW1
        vb1 = beta*vb1 + (1-beta)*db1
        vW2 = beta*vW2 + (1-beta)*dW2
        vb2 = beta*vb2 + (1-beta)*db2

        model.W1 -= lr*vW1
        model.b1 -= lr*vb1
        model.W2 -= lr*vW2
        model.b2 -= lr*vb2

model = MLP()
train_momentum(model)

print("Momentum Output:")
print(np.round(model.forward(X)))

Momentum Output:
[[0.]
 [1.]
 [1.]
 [0.]]


In [ ]:
def train_nesterov(model,epochs=10000,lr=0.1,beta=0.9):
    vW1=np.zeros_like(model.W1)
    vb1=np.zeros_like(model.b1)
    vW2=np.zeros_like(model.W2)
    vb2=np.zeros_like(model.b2)

    for i in range(epochs):
        W1_temp = model.W1 - beta*vW1
        W2_temp = model.W2 - beta*vW2

        model.forward(X)
        dW1,db1,dW2,db2 = model.backward(X,Y)

        vW1 = beta*vW1 + lr*dW1
        vb1 = beta*vb1 + lr*db1
        vW2 = beta*vW2 + lr*dW2
        vb2 = beta*vb2 + lr*db2

        model.W1 -= vW1
        model.b1 -= vb1
        model.W2 -= vW2
        model.b2 -= vb2

model = MLP()
train_nesterov(model)

print("Nesterov Output:")
print(np.round(model.forward(X)))

Nesterov Output:
[[0.]
 [1.]
 [0.]
 [1.]]


In [ ]:
def train_adagrad(model,epochs=10000,lr=0.5,eps=1e-8):
    sW1=np.zeros_like(model.W1)
    sb1=np.zeros_like(model.b1)
    sW2=np.zeros_like(model.W2)
    sb2=np.zeros_like(model.b2)

    for i in range(epochs):
        model.forward(X)
        dW1,db1,dW2,db2 = model.backward(X,Y)

        sW1 += dW1**2
        sb1 += db1**2
        sW2 += dW2**2
        sb2 += db2**2

        model.W1 -= lr*dW1/(np.sqrt(sW1)+eps)
        model.b1 -= lr*db1/(np.sqrt(sb1)+eps)
        model.W2 -= lr*dW2/(np.sqrt(sW2)+eps)
        model.b2 -= lr*db2/(np.sqrt(sb2)+eps)

model = MLP()
train_adagrad(model)

print("Adagrad Output:")
print(np.round(model.forward(X)))

Adagrad Output:
[[0.]
 [0.]
 [1.]
 [1.]]


In [ ]:
def train_adadelta(model,epochs=10000,rho=0.95,eps=1e-6):
    EgW1=np.zeros_like(model.W1)
    EgW2=np.zeros_like(model.W2)
    EdW1=np.zeros_like(model.W1)
    EdW2=np.zeros_like(model.W2)

    for i in range(epochs):
        model.forward(X)
        dW1,db1,dW2,db2 = model.backward(X,Y)

        EgW1 = rho*EgW1 + (1-rho)*dW1**2
        EgW2 = rho*EgW2 + (1-rho)*dW2**2

        updateW1 = -np.sqrt(EdW1+eps)/np.sqrt(EgW1+eps)*dW1
        updateW2 = -np.sqrt(EdW2+eps)/np.sqrt(EgW2+eps)*dW2

        model.W1 += updateW1
        model.W2 += updateW2

model = MLP()
train_adadelta(model)

print("Adadelta Output:")
print(np.round(model.forward(X)))

Adadelta Output:
[[0.]
 [0.]
 [1.]
 [1.]]


In [ ]:
def train_adam(model,epochs=10000,lr=0.01,b1=0.9,b2=0.999,eps=1e-8):
    mW1=np.zeros_like(model.W1)
    vW1=np.zeros_like(model.W1)
    mW2=np.zeros_like(model.W2)
    vW2=np.zeros_like(model.W2)

    for t in range(1,epochs+1):
        model.forward(X)
        dW1,db1,dW2,db2 = model.backward(X,Y)

        mW1 = b1*mW1 + (1-b1)*dW1
        vW1 = b2*vW1 + (1-b2)*(dW1**2)

        mW1_hat = mW1/(1-b1**t)
        vW1_hat = vW1/(1-b2**t)

        model.W1 -= lr*mW1_hat/(np.sqrt(vW1_hat)+eps)

model = MLP()
train_adam(model)

print("Adam Output:")
print(np.round(model.forward(X)))

Adam Output:
[[0.]
 [0.]
 [1.]
 [1.]]


**On breast cancer dataset**

In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

np.random.seed(0)

data = load_breast_cancer()
X = data.data
Y = data.target.reshape(-1,1)

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)

class MLP:
    def __init__(self,input_size,hidden,output):
        self.W1 = np.random.randn(input_size,hidden)*0.01
        self.b1 = np.zeros((1,hidden))
        self.W2 = np.random.randn(hidden,output)*0.01
        self.b2 = np.zeros((1,output))

    def forward(self,X):
        self.z1 = np.dot(X,self.W1)+self.b1
        self.a1 = sigmoid(self.z1)
        self.z2 = np.dot(self.a1,self.W2)+self.b2
        self.a2 = sigmoid(self.z2)
        return self.a2

    def backward(self,X,Y):
        m = X.shape[0]
        dz2 = self.a2 - Y
        dW2 = np.dot(self.a1.T,dz2)/m
        db2 = np.sum(dz2,axis=0,keepdims=True)/m
        dz1 = np.dot(dz2,self.W2.T)*dsigmoid(self.a1)
        dW1 = np.dot(X.T,dz1)/m
        db1 = np.sum(dz1,axis=0,keepdims=True)/m
        return dW1,db1,dW2,db2

def accuracy(model):
    preds = np.round(model.forward(X_test))
    return np.mean(preds==Y_test)*100

In [ ]:
model = MLP(30,16,1)
for i in range(2000):
    model.forward(X_train)
    dW1,db1,dW2,db2 = model.backward(X_train,Y_train)
    model.W1 -= 0.1*dW1
    model.W2 -= 0.1*dW2
print("BGD:",accuracy(model))

BGD: 96.49122807017544


In [ ]:
model = MLP(30,16,1)
for i in range(50):
    for j in range(len(X_train)):
        x=X_train[j:j+1]; y=Y_train[j:j+1]
        model.forward(x)
        dW1,db1,dW2,db2=model.backward(x,y)
        model.W1-=0.01*dW1
        model.W2-=0.01*dW2
print("SGD:",accuracy(model))

SGD: 96.49122807017544


In [ ]:
model = MLP(30,16,1)
for i in range(1000):
    for j in range(0,len(X_train),32):
        x=X_train[j:j+32]; y=Y_train[j:j+32]
        model.forward(x)
        dW1,db1,dW2,db2=model.backward(x,y)
        model.W1-=0.05*dW1
        model.W2-=0.05*dW2
print("MiniBatch:",accuracy(model))

MiniBatch: 97.36842105263158


In [ ]:
model = MLP(30,16,1)
vW1=np.zeros_like(model.W1); vW2=np.zeros_like(model.W2)
for i in range(2000):
    model.forward(X_train)
    dW1,db1,dW2,db2=model.backward(X_train,Y_train)
    vW1=0.9*vW1+0.1*dW1
    vW2=0.9*vW2+0.1*dW2
    model.W1-=0.01*vW1
    model.W2-=0.01*vW2
print("Momentum:",accuracy(model))

Momentum: 86.8421052631579


In [ ]:
model = MLP(30,16,1)
vW1=np.zeros_like(model.W1); vW2=np.zeros_like(model.W2)
for i in range(2000):
    model.forward(X_train)
    dW1,db1,dW2,db2=model.backward(X_train,Y_train)
    vW1=0.9*vW1+0.01*dW1
    vW2=0.9*vW2+0.01*dW2
    model.W1-=vW1
    model.W2-=vW2
print("Nesterov:",accuracy(model))

Nesterov: 96.49122807017544


In [ ]:
model = MLP(30,16,1)
sW1=np.zeros_like(model.W1); sW2=np.zeros_like(model.W2)
for i in range(2000):
    model.forward(X_train)
    dW1,db1,dW2,db2=model.backward(X_train,Y_train)
    sW1+=dW1**2; sW2+=dW2**2
    model.W1-=0.5*dW1/(np.sqrt(sW1)+1e-8)
    model.W2-=0.5*dW2/(np.sqrt(sW2)+1e-8)
print("Adagrad:",accuracy(model))

Adagrad: 95.6140350877193


In [ ]:
model = MLP(30,16,1)

sW1 = np.zeros_like(model.W1)
sW2 = np.zeros_like(model.W2)
sb1 = np.zeros_like(model.b1)
sb2 = np.zeros_like(model.b2)

for i in range(2000):
    model.forward(X_train)
    dW1,db1,dW2,db2 = model.backward(X_train,Y_train)

    sW1 = 0.9*sW1 + 0.1*(dW1**2)
    sW2 = 0.9*sW2 + 0.1*(dW2**2)
    sb1 = 0.9*sb1 + 0.1*(db1**2)
    sb2 = 0.9*sb2 + 0.1*(db2**2)

    model.W1 -= 0.001*dW1/(np.sqrt(sW1)+1e-8)
    model.W2 -= 0.001*dW2/(np.sqrt(sW2)+1e-8)
    model.b1 -= 0.001*db1/(np.sqrt(sb1)+1e-8)
    model.b2 -= 0.001*db2/(np.sqrt(sb2)+1e-8)

print("RMSProp Accuracy:",accuracy(model))

RMSProp Accuracy: 98.24561403508771


In [ ]:
model = MLP(30,16,1)

EgW1 = np.zeros_like(model.W1)
EgW2 = np.zeros_like(model.W2)
EdW1 = np.zeros_like(model.W1)
EdW2 = np.zeros_like(model.W2)

rho = 0.95
eps = 1e-6

for i in range(2000):
    model.forward(X_train)
    dW1,db1,dW2,db2 = model.backward(X_train,Y_train)

    EgW1 = rho*EgW1 + (1-rho)*(dW1**2)
    EgW2 = rho*EgW2 + (1-rho)*(dW2**2)

    updateW1 = -np.sqrt(EdW1+eps)/np.sqrt(EgW1+eps)*dW1
    updateW2 = -np.sqrt(EdW2+eps)/np.sqrt(EgW2+eps)*dW2

    model.W1 += updateW1
    model.W2 += updateW2

    EdW1 = rho*EdW1 + (1-rho)*(updateW1**2)
    EdW2 = rho*EdW2 + (1-rho)*(updateW2**2)

print("Adadelta Accuracy:",accuracy(model))

Adadelta Accuracy: 98.24561403508771


In [ ]:
model = MLP(30,16,1)

mW1 = np.zeros_like(model.W1)
vW1 = np.zeros_like(model.W1)
mW2 = np.zeros_like(model.W2)
vW2 = np.zeros_like(model.W2)

mb1 = np.zeros_like(model.b1)
vb1 = np.zeros_like(model.b1)
mb2 = np.zeros_like(model.b2)
vb2 = np.zeros_like(model.b2)

b1 = 0.9
b2 = 0.999
lr = 0.001
eps = 1e-8

for t in range(1,2001):
    model.forward(X_train)
    dW1,db1,dW2,db2 = model.backward(X_train,Y_train)

    mW1 = b1*mW1 + (1-b1)*dW1
    vW1 = b2*vW1 + (1-b2)*(dW1**2)
    mW2 = b1*mW2 + (1-b1)*dW2
    vW2 = b2*vW2 + (1-b2)*(dW2**2)

    mb1 = b1*mb1 + (1-b1)*db1
    vb1 = b2*vb1 + (1-b2)*(db1**2)
    mb2 = b1*mb2 + (1-b1)*db2
    vb2 = b2*vb2 + (1-b2)*(db2**2)

    mW1_hat = mW1/(1-b1**t)
    vW1_hat = vW1/(1-b2**t)
    mW2_hat = mW2/(1-b1**t)
    vW2_hat = vW2/(1-b2**t)

    mb1_hat = mb1/(1-b1**t)
    vb1_hat = vb1/(1-b2**t)
    mb2_hat = mb2/(1-b1**t)
    vb2_hat = vb2/(1-b2**t)

    model.W1 -= lr*mW1_hat/(np.sqrt(vW1_hat)+eps)
    model.W2 -= lr*mW2_hat/(np.sqrt(vW2_hat)+eps)
    model.b1 -= lr*mb1_hat/(np.sqrt(vb1_hat)+eps)
    model.b2 -= lr*mb2_hat/(np.sqrt(vb2_hat)+eps)

print("Adam Accuracy:",accuracy(model))
print(model.predict(X))
print((model.predict(X) > 0.5).astype(int))

Adam Accuracy: 97.36842105263158


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam
from tensorflow.keras.datasets import cifar10

(X_train, y_train), (X_test, y_test) = cifar10.load_data()

X_train = X_train / 255.0
X_test = X_test / 255.0

X_train_flat = X_train.reshape(-1, 3072)
X_test_flat = X_test.reshape(-1, 3072)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 14s 0us/step


**Batch Gradient Descent**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=SGD(learning_rate=0.01),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=50000,verbose=0)

model.evaluate(X_test_flat, y_test)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1854 - loss: 2.2438


[2.2438247203826904, 0.18539999425411224]

**Stochastic Gradient Descent**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=SGD(learning_rate=0.01),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=1)

model.evaluate(X_test_flat, y_test)

Epoch 1/3
50000/50000 ━━━━━━━━━━━━━━━━━━━━ 114s 2ms/step - accuracy: 0.2731 - loss: 1.9651
Epoch 2/3
50000/50000 ━━━━━━━━━━━━━━━━━━━━ 114s 2ms/step - accuracy: 0.3196 - loss: 1.8680
Epoch 3/3
50000/50000 ━━━━━━━━━━━━━━━━━━━━ 113s 2ms/step - accuracy: 0.3361 - loss: 1.8372
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3254 - loss: 1.8845


[1.8845282793045044, 0.3253999948501587]

**Mini-batch Gradient Descent**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=SGD(learning_rate=0.01),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128,verbose=0)

model.evaluate(X_test_flat, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.3811 - loss: 1.7551


[1.7551361322402954, 0.38109999895095825]

**SGD with Momentum**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

opt = SGD(learning_rate=0.01, momentum=0.9)

model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128,verbose=0)

model.evaluate(X_test_flat, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4378 - loss: 1.5842


[1.5841829776763916, 0.43779999017715454]

**SGD with Nesterov Momentum**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

opt = SGD(learning_rate=0.01, momentum=0.9, nesterov=True)

model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128)

model.evaluate(X_test_flat, y_test)

Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.3560 - loss: 1.8030
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4302 - loss: 1.6130
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4575 - loss: 1.5358
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4325 - loss: 1.6017


[1.6016886234283447, 0.4325000047683716]

**Adagrad**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=Adagrad(learning_rate=0.01),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128)

model.evaluate(X_test_flat, y_test)

Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.3037 - loss: 1.9416
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3790 - loss: 1.7518
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4078 - loss: 1.6758
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4172 - loss: 1.6329


[1.6329034566879272, 0.4171999990940094]

**RMSprop**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=RMSprop(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128)

model.evaluate(X_test_flat, y_test)

Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.2683 - loss: 2.0594
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3562 - loss: 1.7887
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3893 - loss: 1.7057
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4127 - loss: 1.6427


[1.642694354057312, 0.41269999742507935]

**Adadelta**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=Adadelta(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128)

model.evaluate(X_test_flat, y_test)

Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.1343 - loss: 2.3096
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1970 - loss: 2.2191
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2281 - loss: 2.1675
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2428 - loss: 2.1455


[2.145451307296753, 0.24279999732971191]

**Adam**

In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(3072,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_flat, y_train, epochs=3, batch_size=128)

model.evaluate(X_test_flat, y_test)

Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.3169 - loss: 1.9047
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3940 - loss: 1.6930
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4246 - loss: 1.6161
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4322 - loss: 1.5996


[1.5995908975601196, 0.43220001459121704]